server:
  port: 8180
spring:
  application:
    name: @project.artifactId@
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangruigen/config-repository
          username: 1028725142@qq.com
          password: xxxxxxx

