server:
  port: 8041

spring:
  application:
    name: microservice-gateway-zuul-filter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  security:
    enabled: false