server:
  port: 8089
  context-path: /movie-consumer
spring:
  application:
    name: movie-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true