### 服务提供者向eureka server注册的配置

spring:
  application:
    name: @project.artifactId@ #注册到eureka server上的应用名，我这里使用的是artifactId
  cloud:
    service-registry:
      auto-registration:
        enabled: true  #将服务注册到注册中心 默认是true
eureka:
  client:
    service-url:
      #将应用注册到注册中心，配置注册中心地址
      defaultZone: http://peer1:8761/eureka

  instance:
    prefer-ip-address: true #将自己ip注册到eureka server,默认false,如果false,表示将系统所在的hostname注册到eureka server
    #自定义元数据
    metadata-map:
      #key:value形式
      my-metadata: 自定义的元数据