#========================简单的配置eureka server集群

spring:
  application:
    name: microservice-discovery-eureka-ha
eureka:
  client:
    register-with-eureka: true #是否将自己注册到eureka server,由于当前应用就是eureka server ha,所以注册。默认true
    fetch-registry: true #是否从其他eureka server获取注册信息，默认为true。
    service-url:
      #将peer1注册到peer2这个eureka server
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/

---

spring:
  #指定配置文件
  profiles: peer1

server:
  port: 8761
eureka:
  instance:
    #指定当profile=peer1时，主机名是peer1
    hostname: peer1

---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2